{
 "title": "Kubernetes Cluster Resource Summary",
 "description": "This dashboard will help you on maintaining a good TCO (Total Cost of Ownership) for your K8s cluster. You can analyse the overall resources usage Vs request and you can tweak the application resources accordingly.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Zone Resources Stat - Total / Current / Request ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster CPU Usage %",
   "type": "stat",
   "description": "The overall CPU usage of the K8s cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (kube_node_status_capacity{resource=\"cpu\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "description": "Total number of cores on k8s cluster",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage %",
   "type": "stat",
   "description": "Total memory usage of k8s cluster",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (kube_node_status_capacity{resource=\"memory\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "Total memory allocated on k8s cluster",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "Total Mem."
    }
   ]
  },
  {
   "title": "Zone Disk Usage %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=\"/dev/nvme0n1p1\",id=\"/\"}) / sum (container_fs_limit_bytes{device=\"/dev/nvme0n1p1\",id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "stat",
   "description": "Total disk space available on k8s cluster",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/nvme0n1p1\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "description": "This is the sum of CPU request - All namespaces",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Mem Request",
   "type": "stat",
   "description": "Total memory request - All namespaces",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Ephemeral Storage request ",
   "type": "stat",
   "description": "Ephemeral Storage request  - all namespaces",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"ephemeral_storage\"})"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "stat",
   "description": "Total number of used cores",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m]))"
    }
   ]
  },
  {
   "title": "Used Mem.",
   "type": "stat",
   "description": "Total used memory",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/nvme0n1p1\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "K8s cluster CPU Usage",
   "type": "graph",
   "description": "Graph of overall CPU usage of the k8s cluster. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)",
     "legendFormat": "Zone Cpu Util %"
    }
   ]
  },
  {
   "title": "K8s cluster Memory Usage",
   "type": "graph",
   "description": "Graph of overall Memory usage of the k8s cluster. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"})",
     "legendFormat": "Zone Mem. Usage %"
    }
   ]
  },
  {
   "title": "Per cluster CPU & Memory Analysis - Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Analysis Per NameSpace",
   "type": "table",
   "description": "This table will give you an overview of CPU usage per k8s Namespaces. The current table is more focused on request, you can similar columns for other data based on your requirement. \n\nYou can analyse the AVG CPU request usage percentage and based on that you can tweak the application. If the AVG usage is very low you are over provisioning you K8s cluster. You can reduce the request to reduce the node count, and total cost.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (namespace) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests) by (namespace) * 100",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Analysis Per K8s Namespace",
   "type": "table",
   "description": "This table will give you an overview of Memory usage per k8s Namespaces. The current table is more focused on request, you can similar columns for other data based on your requirement. \n\nYou can analyse the AVG Memory request usage percentage and based on that you can tweak the application. If the AVG usage is very low you are over provisioning you K8s cluster. You can reduce the request to reduce the node count, and total cost.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (namespace) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{}) by (namespace) * 100",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Per cluster CPU & Memory Usage - Min/Max/AVG/Current - Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage - Min/Max/Avg/Current",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage - Min/Max/Avg/Current",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (namespace) ",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}